title: "Vijayshree Jayaraman"
description: "Personal website"
baseurl: ""
url: "https://vijayshree-jayaraman.github.io"

theme: minima
plugins:
  - jekyll-feed

# Navigation
nav_pages:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Writing"
    url: /writing/
  - title: "Data"
    url: /data/
  - title: "CV"
    url: /cv/
