title: Your Name
email: you@example.com
description: >
  Personal website showcasing writing, data, and CV in a clean, responsive design.
baseurl: "" 
url: "" 
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
sass:
  style: compressed
