title: "Vijayshree Jayaraman"
email: you@example.com
description: " portfolio site"
baseurl: "" 
url: "" 
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
sass:
  style: compressed

header_pages:
  - public goods.md
  - writing.md
